name: kite
description: "上应小风筝 APP，基于 Flutter。"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Web view and browser related
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.17
  flutter_markdown: ^0.6.9
  flutter_widget_from_html_core: ^0.8.4
  fk_user_agent: ^2.0.1

  # UI
  animations: ^2.0.2
  pull_to_refresh: ^2.0.0
  flash: ^2.0.3+1
  grouped_list: ^4.1.0
  flutter_svg: ^1.0.0
  fl_chart: ^0.40.6
  flutter_native_splash: ^1.3.3
  flutter_weather_bg_null_safety: ^1.0.0

  # Encryption
  encrypt: ^5.0.1  # Used for AES
  crypto: ^3.0.1   # Used for MD5

  # JSON format, encoding and decoding, HTML parser.
  json_serializable: ^6.1.3
  json_annotation: ^4.4.0
  enough_convert: ^1.4.0
  beautiful_soup_dart: ^0.2.0

  # Dio http client
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  dio_log: ^2.0.2

  # Utils
  logger: ^1.1.0
  shared_preferences: ^2.0.11
  provider: ^6.0.2
  check_vpn_connection: ^0.0.2
  nfc_manager: ^3.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  quick_actions: ^0.6.0+9
  universal_platform: ^1.0.0+1

  # Error handlers
  flutter_bugly: ^0.4.3
  flutter_phoenix: ^1.0.0
  catcher: ^0.6.9
  flutter_settings_screens: ^0.3.2-null-safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/home/
    - assets/welcome/
    - assets/connectivity/
    - assets/campus_card/
    - assets/report/
    - assets/fonts/
    - assets/weather/
    - assets/wiki/
    - assets/score/
    - assets/library/
    - assets/timetable/
    - assets/timetable/course/

  fonts:
    # This iconfont file downloaded from ywb.sit.edu.cn
    # which is imported for office module. So I named it office_iconfont.
    - family: office_iconfont
      fonts:
        - asset: assets/fonts/office_iconfont.ttf

flutter_native_splash:
  # Details: https://pub.flutter-io.cn/packages/flutter_native_splash

  color: "#FFFFFF"
  #background_image: "assets/background.png"
  image: assets/icon.png
  fullscreen: true
