theme: jekyll-theme-cayman
github:
  repository_url: "https://github.com/SIT-kite/kite-app"
  ios_url: "https://cn.bing.com"
  android_url: "https://cowtransfer.com/s/e729c623771f4a"
title: "上应小风筝"
baseurl: "/"