name: Bump Build Numer

on:
  push:
    tags:        
      - '*'
  workflow_dispatch:

jobs:
  bump:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.1'
          channel: 'stable'
          
      - name: Bump Flutter Build Number
        run: |
          flutter pub get
          flutter pub global activate cider
          flutter pub global run cider bump build
      
      - name: Get Flutter Version
        id: get_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      
      - name: Update Xcode Build Number
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.get_flutter_version.outputs.version_number }}
          build-number: ${{ steps.get_flutter_version.outputs.build_number }}
          project-path: ios
          
      - name: Get Flutter Version
        id: lastest_flutter_version
        uses: its404/get-flutter-version@v1.0.0
      
      - name: Commit Build Number Update
        run: |
          git add .
          git commit -m "Update: Bump Build Number to ${{ steps.lastest_flutter_version.outputs.build_number }}"
          git push origin master
      
