name: KiteApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Android:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter pub run flutter_native_splash:create
      - run: flutter build apk
      
  build-iOS:
  
    runs-on: macos-latest
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'

    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter pub run flutter_native_splash:create
    - run: flutter build ios --no-codesign

