name: KiteApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Android:
  
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter pub run flutter_native_splash:create
      - run: flutter build apk
      
  build-iOS:
  
    runs-on: macos-latest
    continue-on-error: true
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'

    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter pub run flutter_native_splash:create
    - run: flutter build ios --no-codesign
    
  telegram:
    runs-on: ubuntu-latest
    if: always()
    needs: 
      - build-Android
      - build-iOS
    steps:
    - name: telegram notification
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.BOT_TOKEN }}
        chatId: ${{ secrets.CHAT_ID }}
        jobStatus: ${{ env.WORKFLOW_CONCLUSION }}
        skipSuccess: false

