name: KiteApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-Android:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta' or 'master'
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter pub run flutter_native_splash:create
      - run: flutter build apk --split-per-abi
      - name: 📌 Cache build apk
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: apk-${{ github.ref }}-${{ github.sha }}

      
  build-iOS:
  
    runs-on: macos-latest
    
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'

    - run: flutter pub get
    - run: flutter pub run build_runner build
    - run: flutter pub run flutter_native_splash:create
    - run: flutter build ios --no-codesign
    
  telegram:
    runs-on: ubuntu-latest
    if: always()
    needs: 
      - build-Android
      - build-iOS
    steps:
    - uses: technote-space/workflow-conclusion-action@v2
    - uses: nelonoel/branch-name@v1.0.1
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    
    - name: 📌 Get cache build apk
      uses: actions/cache@v2
      with:
        path: |
          build/
        key: apk-${{ github.ref }}-${{ github.sha }}
        
    - name: 💡 Telegram Notification
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.BOT_TOKEN }}
        chatId: ${{ secrets.CHAT_ID }}
        jobStatus: ${{ env.WORKFLOW_CONCLUSION }}
        skipSuccess: false

      
    - run: cd build/app/outputs/flutter-apk/ && mv app-arm64-v8a-release.apk ${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release.apk
    - name: 🚀 Upload Apk by Bot
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        message: |
          Author: ${{ github.actor }}
          
          Message: ${{ github.event.head_commit.message }}

          See changes: https://github.com/${{ github.repository }}/commit/${{ env.SHA }}
        document: build/app/outputs/flutter-apk/${{ env.BRANCH_NAME }}-${{ env.SHA }}-arm64-v8a-release.apk

