name: Github Pages deploy

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
      - name: archive
        run: |
          cd docs/
          tar --dereference --hard-dereference --directory _site/ -cvf artifact.tar .

