name: Github Pages deploy

on:
  push:


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site

      - run: |
          ls
          sudo ls
          sudo chmod -R 777 .docs/
          cd .docs && ls
          cd _site && ls

      - name: Copy file via SSH
        uses: appleboy/scp-action@v0.1.2
        with:
          host:     ${{ secrets.SERVER_HOST }}
          port:     ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SECRET }}
          source: ".docs/_site/"
          target: "/var/kite/web/"
          strip_components: 1

